# Generated by Django 6.0.3 on 2026-04-22 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0005_company_internshipplacement_company'),
        ('users', '0004_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='placements.company'),
        ),
    ]
