# Generated by Django 6.0.2 on 2026-03-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipplacement',
            name='start_daate',
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='start_date',
            field=models.DateField(default='2026-01-01'),
        ),
        migrations.AlterField(
            model_name='internshipplacement',
            name='end_date',
            field=models.DateField(default='2026-01-01'),
        ),
    ]
