# Generated by Django 6.0.2 on 2026-03-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0002_remove_internshipplacement_start_daate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipplacement',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='internshipplacement',
            name='start_date',
            field=models.DateField(),
        ),
    ]
