# Generated by Django 6.0.2 on 2026-03-16 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0003_alter_internshipplacement_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipplacement',
            name='academic_supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'academic_supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_supervised_placements', to=settings.AUTH_USER_MODEL),
        ),
    ]
