# Generated by Django 6.0.3 on 2026-04-22 14:32

import django.db.models.deletion
from django.db import migrations, models


def populate_companies(apps, schema_editor):
    Company = apps.get_model('placements', 'Company')
    InternshipPlacement = apps.get_model('placements', 'InternshipPlacement')

    for placement in InternshipPlacement.objects.exclude(company_name='').iterator():
        company, _ = Company.objects.get_or_create(name=placement.company_name.strip())
        placement.company_id = company.id
        placement.save(update_fields=['company'])


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0004_internshipplacement_academic_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='placements.company'),
        ),
        migrations.RunPython(populate_companies, migrations.RunPython.noop),
    ]
