# Generated by Django 4.2.29 on 2026-03-24 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logbook', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewaction',
            name='action_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_taken', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewaction',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_actions', to='logbook.weeklylog'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='academic_supervisor',
            field=models.ForeignKey(limit_choices_to={'role': 'academic_supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='logbook.weeklylog'),
        ),
    ]
