# Generated by Django 6.0.2 on 2026-03-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylog',
            name='supervisor_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
