# Generated by Django 6.0.2 on 2026-03-24 09:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_reviewaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewaction',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbook_review_actions', to='logbook.weeklylog'),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='submitted_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
