# Generated by Django 6.0.2 on 2026-04-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0005_alter_reviewaction_log_alter_weeklylog_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklylog',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
